### ISSUE TITLE
编辑策略组中能否增加复选多个节点以实现批量拖动

### ISSUE THREAD

**Issue by RangeKing** [Fndroid/clash-config-builder#1]
首先感谢F大发布的在线构建自定义配置功能。
Wiki中第四步“编辑策略组” 将More中节点拖动至Proxies列表中即可将节点添加至对应策略组，目前我没有发现如何能够批量拖动节点。当节点比较多的时候可能会不太方便。个人觉得增加复选或者全部添加的按钮会更方便使用。

**Comment by Fndroid** [comment]
批量拖动目前受限于使用的库暂时无法增加
